const array = [
  {
    id: 1,
    first_name: "Ame",
    last_name: "Allsobrook",
    email: "aallsobrook0@theglobeandmail.com",
    gender: "Genderfluid",
    age: 28,
  },
  {
    id: 2,
    first_name: "Hyacinthe",
    last_name: "Brumwell",
    email: "hbrumwell1@fotki.com",
    gender: "Bigender",
    age: 88,
  },
  {
    id: 3,
    first_name: "Virginie",
    last_name: "Glendza",
    email: "vglendza2@paginegialle.it",
    gender: "Polygender",
    age: 13,
  },
  {
    id: 4,
    first_name: "Cyril",
    last_name: "Courage",
    email: "ccourage3@arizona.edu",
    gender: "Bigender",
    age: 54,
  },
  {
    id: 5,
    first_name: "Coleman",
    last_name: "Capun",
    email: "ccapun4@twitpic.com",
    gender: "Genderqueer",
    age: 51,
  },
  {
    id: 6,
    first_name: "Cacilie",
    last_name: "Bool",
    email: "cbool5@si.edu",
    gender: "Agender",
    age: 69,
  },
  {
    id: 7,
    first_name: "Ciel",
    last_name: "Tabner",
    email: "ctabner6@people.com.cn",
    gender: "Non-binary",
    age: 41,
  },
  {
    id: 8,
    first_name: "Casandra",
    last_name: "Micklem",
    email: "cmicklem7@hatena.ne.jp",
    gender: "Genderfluid",
    age: 57,
  },
  {
    id: 9,
    first_name: "Sella",
    last_name: "Van Halen",
    email: "svanhalen8@github.com",
    gender: "Male",
    age: 43,
  },
  {
    id: 10,
    first_name: "Munroe",
    last_name: "Arton",
    email: "marton9@disqus.com",
    gender: "Non-binary",
    age: 91,
  },
  {
    id: 11,
    first_name: "Marty",
    last_name: "Monkleigh",
    email: "mmonkleigha@ycombinator.com",
    gender: "Agender",
    age: 95,
  },
  {
    id: 12,
    first_name: "Mick",
    last_name: "Antham",
    email: "manthamb@upenn.edu",
    gender: "Agender",
    age: 38,
  },
  {
    id: 13,
    first_name: "Beth",
    last_name: "Well",
    email: "bwellc@hubpages.com",
    gender: "Bigender",
    age: 99,
  },
  {
    id: 14,
    first_name: "Etty",
    last_name: "Falconbridge",
    email: "efalconbridged@amazon.com",
    gender: "Polygender",
    age: 79,
  },
  {
    id: 15,
    first_name: "Joli",
    last_name: "Thomson",
    email: "jthomsone@marketwatch.com",
    gender: "Genderqueer",
    age: 69,
  },
  {
    id: 16,
    first_name: "Lonny",
    last_name: "McCullock",
    email: "lmccullockf@cbsnews.com",
    gender: "Female",
    age: 7,
  },
  {
    id: 17,
    first_name: "Kelila",
    last_name: "Boik",
    email: "kboikg@house.gov",
    gender: "Bigender",
    age: 72,
  },
  {
    id: 18,
    first_name: "Abrahan",
    last_name: "Boaler",
    email: "aboalerh@deviantart.com",
    gender: "Non-binary",
    age: 49,
  },
  {
    id: 19,
    first_name: "Brett",
    last_name: "Bonick",
    email: "bbonicki@soundcloud.com",
    gender: "Polygender",
    age: 71,
  },
  {
    id: 20,
    first_name: "Rebekkah",
    last_name: "Stapleton",
    email: "rstapletonj@topsy.com",
    gender: "Male",
    age: 55,
  },
  {
    id: 21,
    first_name: "Ruby",
    last_name: "Watman",
    email: "rwatmank@cbsnews.com",
    gender: "Bigender",
    age: 33,
  },
  {
    id: 22,
    first_name: "Rebekah",
    last_name: "Farrier",
    email: "rfarrierl@theguardian.com",
    gender: "Genderqueer",
    age: 67,
  },
  {
    id: 23,
    first_name: "Frazier",
    last_name: "Bowra",
    email: "fbowram@merriam-webster.com",
    gender: "Genderfluid",
    age: 27,
  },
  {
    id: 24,
    first_name: "Rikki",
    last_name: "Ville",
    email: "rvillen@newsvine.com",
    gender: "Genderqueer",
    age: 86,
  },
  {
    id: 25,
    first_name: "Willis",
    last_name: "Bunworth",
    email: "wbunwortho@plala.or.jp",
    gender: "Bigender",
    age: 54,
  },
  {
    id: 26,
    first_name: "Coleman",
    last_name: "Ridewood",
    email: "cridewoodp@smugmug.com",
    gender: "Agender",
    age: 80,
  },
  {
    id: 27,
    first_name: "Grady",
    last_name: "Claibourn",
    email: "gclaibournq@so-net.ne.jp",
    gender: "Male",
    age: 76,
  },
  {
    id: 28,
    first_name: "Glenine",
    last_name: "Hornbuckle",
    email: "ghornbuckler@webs.com",
    gender: "Bigender",
    age: 93,
  },
  {
    id: 29,
    first_name: "Aida",
    last_name: "Simonini",
    email: "asimoninis@opera.com",
    gender: "Polygender",
    age: 61,
  },
  {
    id: 30,
    first_name: "Annadiane",
    last_name: "Reven",
    email: "arevent@goo.gl",
    gender: "Genderfluid",
    age: 25,
  },
  {
    id: 31,
    first_name: "Misha",
    last_name: "Marchand",
    email: "mmarchandu@hugedomains.com",
    gender: "Bigender",
    age: 37,
  },
  {
    id: 32,
    first_name: "Case",
    last_name: "Ralestone",
    email: "cralestonev@canalblog.com",
    gender: "Female",
    age: 54,
  },
  {
    id: 33,
    first_name: "Lulita",
    last_name: "Cocker",
    email: "lcockerw@a8.net",
    gender: "Genderqueer",
    age: 11,
  },
  {
    id: 34,
    first_name: "Lucian",
    last_name: "Palek",
    email: "lpalekx@wunderground.com",
    gender: "Genderfluid",
    age: 80,
  },

  {
    id: 35,
    first_name: "Stanly",
    last_name: "Higounet",
    email: "shigounety@slashdot.org",
    gender: "Non-binary",
    age: 67,
  },
  {
    id: 36,
    first_name: "Alix",
    last_name: "Foden",
    email: "afodenz@t.co",
    gender: "Male",
    age: 26,
  },
  {
    id: 37,
    first_name: "Starlin",
    last_name: "Woodvine",
    email: "swoodvine10@pen.io",
    gender: "Genderqueer",
    age: 67,
  },
  {
    id: 38,
    first_name: "Huberto",
    last_name: "Gove",
    email: "hgove11@bbb.org",
    gender: "Bigender",
    age: 74,
  },
  {
    id: 39,
    first_name: "Angeli",
    last_name: "Heller",
    email: "aheller12@acquirethisname.com",
    gender: "Male",
    age: 24,
  },
  {
    id: 40,
    first_name: "Sherwynd",
    last_name: "Renon",
    email: "srenon13@merriam-webster.com",
    gender: "Bigender",
    age: 40,
  },
  {
    id: 41,
    first_name: "Dorise",
    last_name: "Sole",
    email: "dsole14@adobe.com",
    gender: "Bigender",
    age: 56,
  },
  {
    id: 42,
    first_name: "Siana",
    last_name: "Arkil",
    email: "sarkil15@reverbnation.com",
    gender: "Agender",
    age: 52,
  },
  {
    id: 43,
    first_name: "Diane",
    last_name: "Ludee",
    email: "dludee16@cargocollective.com",
    gender: "Polygender",
    age: 84,
  },
  {
    id: 44,
    first_name: "Matthaeus",
    last_name: "Lancastle",
    email: "mlancastle17@scribd.com",
    gender: "Non-binary",
    age: 9,
  },
  {
    id: 45,
    first_name: "Carmen",
    last_name: "Scard",
    email: "cscard18@uiuc.edu",
    gender: "Genderfluid",
    age: 84,
  },
  {
    id: 46,
    first_name: "Willy",
    last_name: "Hartzog",
    email: "whartzog19@creativecommons.org",
    gender: "Non-binary",
    age: 19,
  },
  {
    id: 47,
    first_name: "Janice",
    last_name: "Chatres",
    email: "jchatres1a@liveinternet.ru",
    gender: "Female",
    age: 16,
  },
  {
    id: 48,
    first_name: "Daile",
    last_name: "Bairstow",
    email: "dbairstow1b@tripod.com",
    gender: "Agender",
    age: 81,
  },
  {
    id: 49,
    first_name: "Fidelio",
    last_name: "McIlenna",
    email: "fmcilenna1c@howstuffworks.com",
    gender: "Polygender",
    age: 8,
  },
  {
    id: 50,
    first_name: "Caprice",
    last_name: "Wherton",
    email: "cwherton1d@europa.eu",
    gender: "Genderqueer",
    age: 94,
  },
];
//
//TODO different tasks for used methods array

// const everyArray = array.every((elem) => elem.age > 18);
// console.log(everyArray);

// const someArr = array.some((elem) => elem.age < 12);
// console.log(someArr);

// const filterArr = array.filter((elem) => elem.gender === "Male");
// console.log(filterArr);

// const findArr = array.find((elem) => elem.first_name === "Caprice");
// console.log(findArr);

const mapArr = array.map((elem) => {
  let clone = { ...elem };
  if (clone.id % 2 === 0) {
    clone.first_name = `${clone.first_name} - disappeared`;
  }
  return clone;
  //return elem.id % 2 === 0 ? {...elem, first_name: `${elem.first_name} - disappeared`} : elem ;
});

console.log(mapArr);
