const array = [
  {
    id: 1,
    first_name: "Cthrine",
    last_name: "Venners",
    email: "cvenners0@twitpic.com",
    gender: "Genderqueer",
    birthday: "3/5/2014",
  },
  {
    id: 2,
    first_name: "Kasey",
    last_name: "Sibbe",
    email: "ksibbe1@usa.gov",
    gender: "Male",
    birthday: "8/13/2020",
  },
  {
    id: 3,
    first_name: "Branden",
    last_name: "Marwood",
    email: "bmarwood2@altervista.org",
    gender: "Non-binary",
    birthday: "10/19/2017",
  },
  {
    id: 4,
    first_name: "Hadria",
    last_name: "Stubbes",
    email: "hstubbes3@ftc.gov",
    gender: "Genderfluid",
    birthday: "9/12/2019",
  },
  {
    id: 5,
    first_name: "Carmelina",
    last_name: "Ardley",
    email: "cardley4@chronoengine.com",
    gender: "Bigender",
    birthday: "8/1/2018",
  },
  {
    id: 6,
    first_name: "Augusta",
    last_name: "Badam",
    email: "abadam5@examiner.com",
    gender: "Agender",
    birthday: "7/29/2018",
  },
  {
    id: 7,
    first_name: "Quintus",
    last_name: "Gagie",
    email: "qgagie6@printfriendly.com",
    gender: "Bigender",
    birthday: "8/27/2017",
  },
  {
    id: 8,
    first_name: "Daryle",
    last_name: "Mayo",
    email: "dmayo7@ifeng.com",
    gender: "Bigender",
    birthday: "8/20/2017",
  },
  {
    id: 9,
    first_name: "Harmony",
    last_name: "Edensor",
    email: "hedensor8@imgur.com",
    gender: "Genderqueer",
    birthday: "1/22/2017",
  },
  {
    id: 10,
    first_name: "West",
    last_name: "Rodliff",
    email: "wrodliff9@digg.com",
    gender: "Polygender",
    birthday: "11/6/2020",
  },
  {
    id: 11,
    first_name: "Dayna",
    last_name: "Steere",
    email: "dsteerea@google.es",
    gender: "Genderqueer",
    birthday: "2/19/2014",
  },
  {
    id: 12,
    first_name: "Lionel",
    last_name: "Lantuffe",
    email: "llantuffeb@wikispaces.com",
    gender: "Polygender",
    birthday: "5/26/2017",
  },
  {
    id: 13,
    first_name: "Richy",
    last_name: "Pitchford",
    email: "rpitchfordc@loc.gov",
    gender: "Female",
    birthday: "2/27/2019",
  },
  {
    id: 14,
    first_name: "Lurleen",
    last_name: "Eustis",
    email: "leustisd@wufoo.com",
    gender: "Polygender",
    birthday: "5/13/2018",
  },
  {
    id: 15,
    first_name: "Adrianne",
    last_name: "Jelliman",
    email: "ajellimane@cnbc.com",
    gender: "Male",
    birthday: "6/2/2013",
  },
  {
    id: 16,
    first_name: "Luisa",
    last_name: "Jiroudek",
    email: "ljiroudekf@ning.com",
    gender: "Genderqueer",
    birthday: "12/29/2017",
  },
  {
    id: 17,
    first_name: "Leonerd",
    last_name: "Yurukhin",
    email: "lyurukhing@wiley.com",
    gender: "Non-binary",
    birthday: "8/15/2014",
  },
  {
    id: 18,
    first_name: "Washington",
    last_name: "Swinburne",
    email: "wswinburneh@networksolutions.com",
    gender: "Polygender",
    birthday: "6/12/2013",
  },
  {
    id: 19,
    first_name: "Maxine",
    last_name: "Vail",
    email: "mvaili@marketwatch.com",
    gender: "Agender",
    birthday: "10/17/2019",
  },
  {
    id: 20,
    first_name: "Dorette",
    last_name: "Butting",
    email: "dbuttingj@loc.gov",
    gender: "Female",
    birthday: "3/2/2016",
  },
  {
    id: 21,
    first_name: "Der",
    last_name: "Witty",
    email: "dwittyk@jigsy.com",
    gender: "Non-binary",
    birthday: "3/17/2020",
  },
  {
    id: 22,
    first_name: "Bjorn",
    last_name: "Concklin",
    email: "bconcklinl@cocolog-nifty.com",
    gender: "Agender",
    birthday: "10/18/2015",
  },
  {
    id: 23,
    first_name: "Monah",
    last_name: "Kording",
    email: "mkordingm@samsung.com",
    gender: "Agender",
    birthday: "10/27/2015",
  },
  {
    id: 24,
    first_name: "Ethan",
    last_name: "Dranfield",
    email: "edranfieldn@sphinn.com",
    gender: "Genderqueer",
    birthday: "2/23/2016",
  },
  {
    id: 25,
    first_name: "Terence",
    last_name: "Giveen",
    email: "tgiveeno@adobe.com",
    gender: "Non-binary",
    birthday: "9/27/2018",
  },
  {
    id: 26,
    first_name: "Marys",
    last_name: "Vinck",
    email: "mvinckp@deliciousdays.com",
    gender: "Male",
    birthday: "9/10/2019",
  },
  {
    id: 27,
    first_name: "Kissie",
    last_name: "Steinhammer",
    email: "ksteinhammerq@myspace.com",
    gender: "Female",
    birthday: "11/22/2016",
  },
  {
    id: 28,
    first_name: "Mitchell",
    last_name: "Duffin",
    email: "mduffinr@infoseek.co.jp",
    gender: "Male",
    birthday: "6/23/2019",
  },
  {
    id: 29,
    first_name: "Winslow",
    last_name: "Waterworth",
    email: "wwaterworths@hp.com",
    gender: "Polygender",
    birthday: "11/3/2016",
  },
  {
    id: 30,
    first_name: "Aigneis",
    last_name: "Looks",
    email: "alookst@webs.com",
    gender: "Male",
    birthday: "9/27/2015",
  },
  {
    id: 31,
    first_name: "Valaree",
    last_name: "Izzatt",
    email: "vizzattu@google.ru",
    gender: "Genderfluid",
    birthday: "7/31/2019",
  },
  {
    id: 32,
    first_name: "Vivian",
    last_name: "Rydeard",
    email: "vrydeardv@csmonitor.com",
    gender: "Bigender",
    birthday: "5/18/2013",
  },
  {
    id: 33,
    first_name: "Wilhelmina",
    last_name: "Beedie",
    email: "wbeediew@mail.ru",
    gender: "Male",
    birthday: "9/27/2017",
  },
  {
    id: 34,
    first_name: "Britni",
    last_name: "Sloper",
    email: "bsloperx@nytimes.com",
    gender: "Male",
    birthday: "11/24/2017",
  },
  {
    id: 35,
    first_name: "Thorn",
    last_name: "Riddoch",
    email: "triddochy@google.com",
    gender: "Genderqueer",
    birthday: "9/27/2018",
  },
  {
    id: 36,
    first_name: "Daniela",
    last_name: "Byk",
    email: "dbykz@nih.gov",
    gender: "Agender",
    birthday: "2/17/2016",
  },
  {
    id: 37,
    first_name: "Siouxie",
    last_name: "Cawdron",
    email: "scawdron10@hibu.com",
    gender: "Genderqueer",
    birthday: "1/29/2014",
  },
  {
    id: 38,
    first_name: "Munroe",
    last_name: "Costain",
    email: "mcostain11@tinyurl.com",
    gender: "Bigender",
    birthday: "3/29/2018",
  },
  {
    id: 39,
    first_name: "Gerrie",
    last_name: "Geldart",
    email: "ggeldart12@microsoft.com",
    gender: "Male",
    birthday: "7/3/2013",
  },
  {
    id: 40,
    first_name: "Lindsey",
    last_name: "Hrachovec",
    email: "lhrachovec13@sfgate.com",
    gender: "Female",
    birthday: "3/10/2021",
  },
  {
    id: 41,
    first_name: "Neel",
    last_name: "Corry",
    email: "ncorry14@ycombinator.com",
    gender: "Polygender",
    birthday: "9/21/2019",
  },
  {
    id: 42,
    first_name: "Lilah",
    last_name: "Sharkey",
    email: "lsharkey15@cbsnews.com",
    gender: "Genderfluid",
    birthday: "7/30/2017",
  },
  {
    id: 43,
    first_name: "Sashenka",
    last_name: "Stoyle",
    email: "sstoyle16@cornell.edu",
    gender: "Bigender",
    birthday: "3/29/2021",
  },
  {
    id: 44,
    first_name: "Hale",
    last_name: "Pockey",
    email: "hpockey17@marketwatch.com",
    gender: "Genderfluid",
    birthday: "11/8/2019",
  },
  {
    id: 45,
    first_name: "Goldie",
    last_name: "Ginty",
    email: "gginty18@adobe.com",
    gender: "Male",
    birthday: "3/21/2013",
  },
  {
    id: 46,
    first_name: "Tamara",
    last_name: "Korneichik",
    email: "tkorneichik19@alexa.com",
    gender: "Bigender",
    birthday: "9/7/2020",
  },
  {
    id: 47,
    first_name: "Kendal",
    last_name: "Cauthra",
    email: "kcauthra1a@cnn.com",
    gender: "Non-binary",
    birthday: "6/14/2020",
  },
  {
    id: 48,
    first_name: "Hube",
    last_name: "Gwynne",
    email: "hgwynne1b@4shared.com",
    gender: "Genderqueer",
    birthday: "3/28/2014",
  },
  {
    id: 49,
    first_name: "Milissent",
    last_name: "Osgodby",
    email: "mosgodby1c@t.co",
    gender: "Non-binary",
    birthday: "9/28/2014",
  },
  {
    id: 50,
    first_name: "Brandais",
    last_name: "McCombe",
    email: "bmccombe1d@yolasite.com",
    gender: "Male",
    birthday: "3/2/2014",
  },
];

const obj = array[1];
const checkYearBirth = function () {
  let date = new Date(this.birthday);
  let dateYear = date.getFullYear();
  return dateYear < 2014;
};
obj.isAdalt = checkYearBirth;
console.log(obj.isAdalt());
